name: Release jb
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact-name: linux-x86
          - os: ubuntu-24.04-arm
            artifact-name: linux-arm64
          - os: macos-latest
            artifact-name: macos-arm64
          - os: windows-latest
            artifact-name: windows
    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Build executable
        run: dart dartle.dart distribution

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"
        shell: bash

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/jb.tar.gz
          asset_name: jb-${{ steps.get_version.outputs.VERSION }}-${{ matrix.artifact-name }}.tar.gz
          asset_content_type: application/gzip
